// Web3-Config Options
export const SET_WEB3 = 'SET_WEB3';
export const SET_CONTRACT_INSTANCE = 'SET_CONTRACT_INSTANCE';

// Survey Actions
export const SET_SURVEY_FACTORY_CONTRACT_INSTANCE = 'SET_SURVEY_FACTORY_CONTRACT_INSTANCE';
export const GET_SURVEYS = 'GET_SURVEYS';
export const CREATE_SURVEY = 'CREATE_SURVEY';
export const GET_SURVEY = 'GET_SURVEY';
export const ANSWER_SURVEY_QUESTIONS = 'ANSWER_SURVEY_QUESTIONS';
export const SET_CURRENT_ADDRESS = 'SET_CURRENT_ADDRESS';
export const GET_SURVEY_BALANCE = 'GET_SURVEY_BALANCE';
