export const SET_WEB3 = 'SET_WEB3';
export const SET_CONTRACT_INSTANCE = 'SET_CONTRACT_INSTANCE';
export const SET_SURVEY_FACTORY_CONTRACT_INSTANCE = 'SET_SURVEY_FACTORY_CONTRACT_INSTANCE';
export const GET_SURVEYS = 'GET_SURVEYS';
